/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitesIndexRouteImport } from './routes/sites/index'
import { Route as CrawlsIndexRouteImport } from './routes/crawls/index'
import { Route as SitesNewRouteImport } from './routes/sites/new'
import { Route as SitesSiteIdRouteImport } from './routes/sites/$siteId'
import { Route as CrawlsCrawlIdRouteImport } from './routes/crawls/$crawlId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIndexRoute = SitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlsIndexRoute = CrawlsIndexRouteImport.update({
  id: '/crawls/',
  path: '/crawls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesNewRoute = SitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)
const CrawlsCrawlIdRoute = CrawlsCrawlIdRouteImport.update({
  id: '/crawls/$crawlId',
  path: '/crawls/$crawlId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/crawls/$crawlId': typeof CrawlsCrawlIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/crawls/': typeof CrawlsIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/crawls/$crawlId': typeof CrawlsCrawlIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/crawls': typeof CrawlsIndexRoute
  '/sites': typeof SitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/crawls/$crawlId': typeof CrawlsCrawlIdRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/sites/new': typeof SitesNewRoute
  '/crawls/': typeof CrawlsIndexRoute
  '/sites/': typeof SitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/crawls/$crawlId'
    | '/sites/$siteId'
    | '/sites/new'
    | '/crawls/'
    | '/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/crawls/$crawlId'
    | '/sites/$siteId'
    | '/sites/new'
    | '/crawls'
    | '/sites'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/crawls/$crawlId'
    | '/sites/$siteId'
    | '/sites/new'
    | '/crawls/'
    | '/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CrawlsCrawlIdRoute: typeof CrawlsCrawlIdRoute
  SitesSiteIdRoute: typeof SitesSiteIdRoute
  SitesNewRoute: typeof SitesNewRoute
  CrawlsIndexRoute: typeof CrawlsIndexRoute
  SitesIndexRoute: typeof SitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/': {
      id: '/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof SitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawls/': {
      id: '/crawls/'
      path: '/crawls'
      fullPath: '/crawls/'
      preLoaderRoute: typeof CrawlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/new': {
      id: '/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof SitesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crawls/$crawlId': {
      id: '/crawls/$crawlId'
      path: '/crawls/$crawlId'
      fullPath: '/crawls/$crawlId'
      preLoaderRoute: typeof CrawlsCrawlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CrawlsCrawlIdRoute: CrawlsCrawlIdRoute,
  SitesSiteIdRoute: SitesSiteIdRoute,
  SitesNewRoute: SitesNewRoute,
  CrawlsIndexRoute: CrawlsIndexRoute,
  SitesIndexRoute: SitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
